/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-11-30 08:18:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.term_005fjsp_005f11_005f28_005fbackup.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import termpackage.DBConnection;
import java.io.File;
import javax.servlet.http.Part;
import java.io.IOException;

public final class item_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("javax.servlet.http.Part");
    _jspx_imports_classes.add("java.io.IOException");
    _jspx_imports_classes.add("java.io.File");
    _jspx_imports_classes.add("termpackage.DBConnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    String username = (String) session.getAttribute("username");


	if (username == null) {
	    // 로그인이 안된 경우 경고 문구와 리다이렉트 설정
	    out.println("<script>alert('로그인을 하셔야 이용하실 수 있습니다.'); location.href='../html/login.html';</script>");
	    return; // 이후 코드 실행 방지
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>상품 등록</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../styles.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/item.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"overflow-x: hidden\">\r\n");
      out.write("\r\n");
      out.write("    <!-- 상단 -->\r\n");
      out.write("	<header class=\"header\">\r\n");
      out.write("        <img src=\"../images/top_banner.svg\" alt=\"맨위 로고\" class=\"top-bar\">\r\n");
      out.write("        <div class=\"search-bar\">\r\n");
      out.write("            <a href=\"../index.jsp\"><img src=\"../images/main_logo.svg\" alt=\"로고\" class=\"logo\"></a>\r\n");
      out.write("            <form id=\"searchForm\" action=\"search_result.jsp\" method=\"GET\">\r\n");
      out.write("                <div class=\"search-input-container\">\r\n");
      out.write("                    <input type=\"text\" placeholder=\"🔍 물품명, 장터명, 카테고리 태그 등\" class=\"search-input\" id=\"searchInput\" name=\"query\">\r\n");
      out.write("                    <button type=\"submit\" class=\"search-button\" id=\"searchButton\">🔍</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            <div class=\"icons\">\r\n");
      out.write("                <a href=\"bookmark.jsp\"><span><img src=\"../images/bookmark01.png\" alt=\"북마크\" class=\"icons\"></span></a>\r\n");
      out.write("                <span><img src=\"../images/favorite01.png\" alt=\"즐겨찾기\" class=\"icons\"></span>\r\n");
      out.write("                <a href=\"my_interface.jsp\"><span><img src=\"../images/interpace01.png\" alt=\"내정보\" class=\"icons\"></span></a>\r\n");
      out.write("\r\n");
      out.write("                ");
 
                // 로그인 상태 확인 후 아이디와 로그아웃 버튼 표시
                if (username != null) { 
                
      out.write("\r\n");
      out.write("                    <span class=\"username-display\">");
      out.print( username );
      out.write("</span>\r\n");
      out.write("                    <a href=\"../html/logout.jsp\">\r\n");
      out.write("                        <input type=\"button\" class=\"logout-button\" value=\"로그아웃\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                ");
 
                } else { 
                
      out.write("\r\n");
      out.write("                    <a href=\"../html/login.html\">\r\n");
      out.write("                        <input type=\"button\" class=\"login-button\" value=\"로그인\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                ");
 
                } 
                
      out.write("\r\n");
      out.write("             </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"menu-bar\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\"><img src=\"../images/category.svg\" alt=\"카테고리\">카테고리</a></li>\r\n");
      out.write("                <li><a href=\"../index.html#my-wants\">내가 원해요</a></li>\r\n");
      out.write("                <li><a href=\"../index.html#others-wants\">상대방이 원해요</a></li>     \r\n");
      out.write("                <li><a href=\"#\">급상승</a></li>\r\n");
      out.write("                <li><a href=\"#\">쏙</a></li>\r\n");
      out.write("                <li><a href=\"#\">이벤트</a></li>\r\n");
      out.write("                <li><a href=\"item.jsp\">상품등록</a></li>\r\n");
      out.write("                \r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("        \r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("<main>\r\n");
      out.write("    <div class=\"item-interface-container\">\r\n");
      out.write("        <h2>물품 정보</h2>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"item_process.jsp\" method=\"POST\" enctype=\"multipart/form-data\">\r\n");
      out.write("            <!-- 물품 이미지 업로드 -->\r\n");
      out.write("            <div class=\"item-img\">\r\n");
      out.write("                <span id=\"image-count\">물품 이미지(0/10)</span>\r\n");
      out.write("                <div class=\"photo-upload-container\">\r\n");
      out.write("                    <div class=\"upload-box\" id=\"custom-upload-box\"><img src=\"../images/add-photo.svg\" alt=\"이미지등록\">이미지 등록</div>\r\n");
      out.write("                    <input type=\"file\" id=\"photo-input\" name=\"pd_image\" accept=\"image/*\" multiple hidden>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"photo-preview\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 물품명 -->\r\n");
      out.write("            <div class=\"item-input-container\">\r\n");
      out.write("                <span id=\"image-count\">물품명</span>\r\n");
      out.write("                <input type=\"text\" placeholder=\"물품명을 입력해주세요\" class=\"item-input\" name=\"pd_name\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 가격 -->\r\n");
      out.write("            <div class=\"item-input-container\">\r\n");
      out.write("                <span id=\"image-count\">가격</span>\r\n");
      out.write("                <input type=\"text\" placeholder=\"가격을 입력해주세요\" class=\"item-input\" name=\"pd_price\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 설명 -->\r\n");
      out.write("            <div id=\"details\">\r\n");
      out.write("                <span id=\"image-count\">물품 설명</span>\r\n");
      out.write("                <textarea id=\"item_details\" name=\"pd_information\" rows=\"4\" cols=\"50\" placeholder=\"물품에 대한 자세한 설명을 적어주세요.\"></textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 카테고리 및 상태 선택 -->\r\n");
      out.write("            <div class=\"item-cartegory-container\">\r\n");
      out.write("                <span id=\"image-count\">카테고리</span>\r\n");
      out.write("                <select class=\"item-cartegory\" name=\"category\">\r\n");
      out.write("                    <option value=\"\" disabled selected>선택</option>\r\n");
      out.write("                    <option value=\"노트북\">노트북</option>\r\n");
      out.write("                    <option value=\"지이잉\">지이잉</option>\r\n");
      out.write("                    <option value=\"기타\">기타</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 거래 방식 -->\r\n");
      out.write("            <div class=\"item-trade-container\">\r\n");
      out.write("                <span id=\"image-count\">거래방식</span>\r\n");
      out.write("                <div class=\"trade-title-container\">\r\n");
      out.write("                    <div class=\"trade-system\">\r\n");
      out.write("                        <div class=\"trade-system-checkbox\">\r\n");
      out.write("                            <div class=\"meet\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"meet-checkbox\" name=\"trade_meet\">직거래\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"post\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"post-checkbox\" name=\"trade_post\">택배\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("				<div class=\"trade-method\">\r\n");
      out.write("				    <div class=\"exchange\">\r\n");
      out.write("				        <div class=\"trade-box\">\r\n");
      out.write("				            <label id=\"trade-icon\">\r\n");
      out.write("				                <input type=\"checkbox\" id=\"trade-checkbox\" name=\"trade_exchange\"> \r\n");
      out.write("				                <img src=\"../images/trade-icon.svg\" alt=\"물물교환 아이콘\" id=\"trade-icon\">\r\n");
      out.write("				                물물교환\r\n");
      out.write("				            </label>\r\n");
      out.write("				        </div>\r\n");
      out.write("				        <!-- 물물교환용 입력 필드 -->\r\n");
      out.write("				        <div id=\"tradeInput\" class=\"hidden\">\r\n");
      out.write("				            <label for=\"tradeText\">희망 가격:</label>\r\n");
      out.write("				            <input type=\"text\" id=\"tradeText\" name=\"trade_price\" placeholder=\"0원 ~\">\r\n");
      out.write("				            <span>~</span>\r\n");
      out.write("				            <input type=\"text\" id=\"tradeText\" name=\"trade_max_price\" placeholder=\"~ 999,999,999원\">원\r\n");
      out.write("				        </div>\r\n");
      out.write("				    </div>\r\n");
      out.write("				    <div class=\"sell\">\r\n");
      out.write("				        <div class=\"sell-box\">\r\n");
      out.write("				            <label id=\"sell-icon\">\r\n");
      out.write("				                <input type=\"checkbox\" id=\"sell-checkbox\" name=\"trade_sell\">\r\n");
      out.write("				                <img src=\"../images/sell-icon.svg\" alt=\"판매 아이콘\" id=\"sell-icon\">\r\n");
      out.write("				                판매\r\n");
      out.write("				            </label>\r\n");
      out.write("				        </div>\r\n");
      out.write("				        <!-- 판매용 입력 필드 -->\r\n");
      out.write("				        <div id=\"sellInput\" class=\"hidden\">\r\n");
      out.write("				            <label for=\"sellText\">판매 금액:</label>\r\n");
      out.write("				            <input type=\"text\" id=\"sellText\" name=\"sell_price\" placeholder=\"0원 ~ 999,999,999원\">원\r\n");
      out.write("				        </div>\r\n");
      out.write("				    </div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 물품 상태 -->\r\n");
      out.write("            <div class=\"item-condition\">\r\n");
      out.write("                <span id=\"image-count\">물품 상태</span>\r\n");
      out.write("                <fieldset>\r\n");
      out.write("                    <div class=\"radio-group\">\r\n");
      out.write("                        <label>\r\n");
      out.write("                            <input type=\"radio\" name=\"pd_status\" value=\"new_item\" required>\r\n");
      out.write("                            <span>새 물품(미사용)</span>\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <label>\r\n");
      out.write("                            <input type=\"radio\" name=\"pd_status\" value=\"no_usage\">\r\n");
      out.write("                            <span>사용감 없음</span>\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <label>\r\n");
      out.write("                            <input type=\"radio\" name=\"pd_status\" value=\"light_usage\">\r\n");
      out.write("                            <span>사용감 적음</span>\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <label>\r\n");
      out.write("                            <input type=\"radio\" name=\"pd_status\" value=\"heavy_usage\">\r\n");
      out.write("                            <span>사용감 많음</span>\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <label>\r\n");
      out.write("                            <input type=\"radio\" name=\"pd_status\" value=\"broken\">\r\n");
      out.write("                            <span>고장/파손 물품</span>\r\n");
      out.write("                        </label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </fieldset>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 거래 희망 지역 -->\r\n");
      out.write("            <div class=\"location-select-container\">\r\n");
      out.write("                <span id=\"image-count\">거래 희망 지역</span>\r\n");
      out.write("                <select class=\"location-select\" name=\"location_1\">\r\n");
      out.write("                    <option value=\"\" disabled selected>선택</option>\r\n");
      out.write("                    <option value=\"서울\">서울</option>\r\n");
      out.write("                    <option value=\"부산\">부산</option>\r\n");
      out.write("                    <option value=\"대구\">대구</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <span class=\"separator\"> > </span>\r\n");
      out.write("                <select class=\"location-select\" name=\"location_2\">\r\n");
      out.write("                    <option value=\"\" disabled selected>선택</option>\r\n");
      out.write("                    <option value=\"서울어딘가\">서울어딘가</option>\r\n");
      out.write("                    <option value=\"어디어딘가\">어디어딘가</option>\r\n");
      out.write("                    <option value=\"어딘가\">어딘가</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 제출 버튼 -->\r\n");
      out.write("            <div id=\"upload-container\">\r\n");
      out.write("                <button id=\"upload-button\" type=\"submit\">상품 등록</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      out.write("    <script src=\"../scripts.js\"></script>\r\n");
      out.write("    <script src=\"../js/itemscripts.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
